name: CD GitOps

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout do codigo: está no repo e baixar na máquina do github
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Build e push da imagem para o Dockerhub
      - name: Build and push imagem to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gitops-fc-node
          tags: ${{ github.sha }}, latest
